
new_tab Data Engineering
layout splits
cd ~/Documents/github/marvin/data-engineering
launch
launch --location=hsplit

new_tab Marvin Suite
layout splits
cd ~/Documents/github/marvin/marvin-suite
launch
launch --location=hsplit

new_tab Keystone
layout splits
cd ~/Documents/github/marvin/keystone
launch
launch --location=hsplit

new_tab Marvin
cd ~/Documents/github/marvin
launch
