
new_tab "Data Engineering"
cd ~/Documents/github/marvin/data-engineering
launch

new_tab "Service Apps"
cd ~/Documents/github/marvin/service-apps
launch --location=vsplit
launch --location=vsplit

new_tab "Marvin"
cd ~/Documents/github/marvin
launch

new_tab "Coach"
cd ~/Documents/github/marvin/coach
launch --location=vsplit
launch --location=vsplit

new_tab "Marvin Suite"
cd ~/Documents/github/marvin/marvin-suite
launch --location=vsplit
