#!/usr/bin/env bash
# Example workflow for managing opencode with dotfiles

echo "🚀 OpenCode Management Workflow Example"
echo "========================================"
echo ""

# 1. Initial setup on a new machine
echo "1. Initial Setup on New Machine:"
echo "   ------------------------------"
echo "   # Install opencode if not present"
echo "   curl -fsSL https://opencode.ai/install | sh"
echo ""
echo "   # Apply dotfiles configuration"
echo "   cd ~/Documents/GitHub/dotfiles"
echo "   ./script/opencode setup apply"
echo "   ./script/opencode setup env"
echo "   source ~/.config/opencode/env.sh"
echo ""

# 2. Daily usage and monitoring
echo "2. Daily Usage & Monitoring:"
echo "   --------------------------"
echo "   # Quick status check"
echo "   oc status"
echo ""
echo "   # Monitor memory usage"
echo "   ocmem"
echo ""
echo "   # Run health checks"
echo "   oc doctor"
echo ""

# 3. Memory management when usage is high
echo "3. Memory Management (when >500MB):"
echo "   ---------------------------------"
echo "   # Check detailed stats"
echo "   ./script/opencode memory stats"
echo ""
echo "   # Clean up cache"
echo "   ./script/opencode memory cleanup"
echo ""
echo "   # Apply optimizations"
echo "   ./script/opencode memory optimize"
echo ""
echo "   # Restart if >800MB"
echo "   ./script/opencode memory restart"
echo ""

# 4. Synchronization with dotfiles
echo "4. Synchronization with Dotfiles:"
echo "   -------------------------------"
echo "   # Save current config to dotfiles"
echo "   ocpush"
echo ""
echo "   # Apply templates from dotfiles"
echo "   ocpull"
echo ""
echo "   # Force apply templates (overwrites local)"
echo "   ./script/opencode sync pull --force"
echo ""

# 5. Troubleshooting common issues
echo "5. Troubleshooting:"
echo "   -----------------"
echo "   # Models stuck or slow:"
echo "   # Check timeout settings"
echo "   cat ~/.config/opencode/opencode.json"
echo ""
echo "   # High memory (>800MB):"
echo "   ./script/opencode memory restart"
echo ""
echo "   # Configuration issues:"
echo "   ./script/opencode setup reset"
echo "   ./script/opencode setup apply"
echo ""

echo "📚 Quick Reference Card:"
echo "   oc help           - Show all commands"
echo "   oc status         - Current status"
echo "   oc doctor         - Health checks"
echo "   ocmem             - Memory monitor"
echo "   ocsetup           - Apply optimizations"
echo "   ocpush/ocpull     - Sync with dotfiles"
echo ""

echo "🔧 Configured Limits:"
echo "   - Memory warning: 500MB"
echo "   - Auto-restart: 800MB"
echo "   - Provider timeout: 5min"
echo "   - Max sessions: 200"
echo "   - Cache cleanup: 30min"
echo ""

echo "✅ Done! Your opencode is now properly managed with dotfiles."